on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Nix and use that to run our tests so our environment matches exactly.
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    # Run our checks to catch quick issues
    - run: nix flake check

    # Run our go tests within the context of the dev shell from the flake. This
    # will ensure we have all our dependencies.
    - name: test
      run: nix develop -c zig build test-unit

    # Test our full build
    - name: build
      run: |
        nix build .
